version: '3.8'

services:
  # Main service for building and pushing to Docker Hub
  isaac-lab:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: bys724/isaac-lab:latest
    container_name: isaac-lab
    hostname: isaac-lab
    runtime: nvidia
    environment:
      - DISPLAY=${DISPLAY:-:0}
      - ACCEPT_EULA=Y
      - PRIVACY_CONSENT=Y
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - QT_X11_NO_MITSHM=1
      - WANDB_API_KEY=${WANDB_API_KEY:-}
      - WANDB_PROJECT=${WANDB_PROJECT:-isaac-lab}
    volumes:
      # X11 socket for GUI support
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      # Optional: Mount workspace for testing
      - ./workspace:/workspace:rw
    network_mode: host
    privileged: true
    stdin_open: true
    tty: true
    command: bash
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

networks:
  default:
    driver: bridge